name: test_olusturucu
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  file_picker: ^8.1.3
  pdf: ^3.8.4
  path_provider: ^2.0.15
  image_picker: ^1.1.2
  image_cropper: ^8.0.2
  provider: ^6.0.5
  syncfusion_flutter_pdf: ^27.1.57
  syncfusion_flutter_pdfviewer: ^27.1.57

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
